### ISSUE TITLE
2.5.6 -> 2.5.7 broke TLS imap for specific server

### ISSUE THREAD

**Issue by rhavenn** [lefcha/imapfilter#94] opened 2015-06-10 21:48 UTC
FreeBSD recently upgraded their package for imapfilter from 2.5.6 -> 2.5.7 . One of the servers I connect to via IMAP breaks. Downgrading my packages to 2.5.6 fixes the issue with zero other changes. Perhaps something in the server headers?

I use securetls = true and ssl is set to tls1 . tls1.1 and 1.2 aren't supported, it seems, by the server.

I call imapfilter with:
````
/usr/local/bin/imapfilter -c ~/Mail/.imapfilter.config
```

and this produces:
```
imapfilter: login request to account@domain@secure.emailsrvr.com failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	/usr/local/share/imapfilter/account.lua:68: in function '_check_result'
	/usr/local/share/imapfilter/account.lua:84: in function '_login_user'
	/usr/local/share/imapfilter/account.lua:46: in function 'IMAP'
	/home/rhavenn/Mail/.imapfilter.config:28: in main chunk
```

I have not tried without SSL, but can if it would help. I pull my password via:
```
function get_imap_password(file)
        local home = os.getenv("HOME")
        local file = home .. "/mail/" .. file
        local str = io.open(file):read()
        return str;
end
```

and use that via:
```
local account = IMAP {
        server = 'secure.emailsrvr.com',
        username = 'account',
        password = get_imap_password(".imap.config"),
        ssl = 'tls1',
}
```

in case it's something, possibly, with the email password parser.

**Comment by rhavenn** [comment] 2015-06-10 22:21
server connect via telnet 143 shows:
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=TOKEN] Server ready director3.mail.ord1c.rsapps.net
1 CAPABILITY
* CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=TOKEN

**Comment by lefcha** [comment] 2015-06-11 20:20
I think this specific server supports TLSv1, TLSv1.1 and TLSv1.2, while it doesn't support SSLv3, and you can verify this with OpenSSL by having a look at whether a connection has been established with commands such as:

```sh
openssl s_client -host secure.emailsrvr.com -port 993 -ssl3
openssl s_client -host secure.emailsrvr.com -port 993 -tls1
openssl s_client -host secure.emailsrvr.com -port 993 -tls1_1
openssl s_client -host secure.emailsrvr.com -port 993 -tls1_2
```

You could try executing imapfilter with the `-d debugfile` option, in case we get more information on the error.  You could also use the `-l logfile` option in case something is written there, too.

One change that might be related to this problem is that version 2.5.7 uses the CA certificates in the systems SSL CA TrustStore directory to validate a server's certificate, and when this isn't possible the local certificates file is used (as was the case for vesion 2.5.6).  That's why you could first try moving your `~/.imapfilter/certificates` somewhere else, so imapfilter doesn't use that, so we can see what happens then.

Let's start with the above and we can see if we find anything useful to continue...

**Comment by 5u623l20** [comment] 2015-06-18 20:20
@lefcha From the reporter the problem still persists in 2.6.
@rhavenn Can you check issue number 91 where someone mentioned about an error on Apple. As Apple ~ FreeBSD you should give it a try although I am not sure whether if both indicates same problem. 3:)

**Comment by rhavenn** [comment] 2015-06-22 23:32
I saw #91, but that didn't seem to apply.  I'm currently rebuilding 2.6, so perhaps that will fix it.

If I turn off SSL it works fine, so definitely something in the SSL piece. Switching to tsl1_2 doesn't changing anything. 

Is there a hard path for finding the SSL cert? or system call you use? FreeBSD core SSL doesn't ship with a cert file and the port may not either. Normally, packages rely on on the nss (Netscape Security Services from Mozilla) package to supply the ca certificate file.

**Comment by rhavenn** [comment] 2015-06-23 18:54
2.6 has the same issue.

My openssl versions:
/usr/bin/openssl - OpenSSL 1.0.1l-freebsd
/usr/local/bin/openssl - OpenSSL 1.0.2c

**Comment by lefcha** [comment] 2015-06-23 21:26
I think you missed my previous reply a few posts above.  Can you have a look at it, and let me know how it went trying the things I suggested there?

**Comment by rhavenn** [comment] 2015-06-24 06:33
Sorry, I did try them, but get no additional output.

`imapfilter -d imap.debug -c ~user/Mail/.imapfilter.config`   -  this is empty
`imapfilter -d imap.debug -l imap.log -c ~user/Mail/.imapfilter.config`    - this shows the same as the original error

Moving the .imapfilter/certificates files does nothing. It never prompts to re-validate the cert, so it's failing prior to that. The error is the same.

running `openssl s_client -host secure.emailsrvr.com -port 993 -tls1_1` 
running `openssl s_client -host secure.emailsrvr.com -port 993 -tls1_2`

These both fail with:
34381940600:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:
which seems to mean that the version isn't supported. The only one that works is:
`openssl s_client -host secure.emailsrvr.com -port 993 -tls1` 

  shows it as connecting and I get a cert.

That being said, this doesn't change the error in anyway if I switch  ssl = 'tls1' to  ssl = 'tls1_2' . If I go back to imapfilter 2.5.6 this will throw an error about an invalid TLS version setting.

This is why I think it's something more to do with how it's loading the SSL libs themselves or failing to even load them or failing someplace else. Looking at your source for imapfilter.c you've got `opts.truststore = "/etc/ssl/certs";` and a 't' option. Setting that to '/usr/local/etc/ssl' doesn't seem to help.

**Comment by lefcha** [comment] 2015-06-24 17:51
I think I know what the problem is here, and I have made a change to the code that should fix this problem.  Can you get the current code in git, compile it and try again executing your config? Thanks!

**Comment by rhavenn** [comment] 2015-06-25 06:01
Yes, that fixed the issue. Thanks a lot.

**Comment by Papafox** [comment] 2015-06-25 07:10
See my comment on the fix.

I'm deeply concerned about this fix.  While it may be secure, I'm concerned that it may possibly allow invalid certificates.  The current logic will only allow self-signed certificates to be matched against the local certs file. The certificate from secure.emailsrvr.com should be verified by the `'/etc/ssl/certs/AddTrust_External_Root.pem'` cert in the truststore, and as such it should not need to look at the certs file.

I'll do further testing over the weekend and get back to you.

**Comment by lefcha** [comment] 2015-06-25 19:46
@Papafox I have answered your comment in the commit, and probably you're right that the verification should be taken more seriously when there's a failure, but at the same time users would like to filter their mail, and with this change they are given the choice to have a look at the certificate and decide themselves if they should accept it or not, and put it in the local imapfilter certificates file.

I'm not sure if imapfilter should just be less strict with the cause of this error (`secure.emailsrvr.com` seems to cause a `X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN` error), or if this means that the server has a problem that should be solved by its admins, or that the system has a problem with its truststore...

A solution to this could be to be as strict with verification errors as before, but warn the user about the failure, and let him decide if the connection should continue, but this should probably not be asked every time imapfilter is executed, because the server might always have a problem with its certificate..

**Comment by rhavenn** [comment] 2015-06-26 04:51
The openssl command by default doesn't use a CA file, so maybe that's why you're seeing it fail?

`openssl s_client -host secure.emailsrvr.com -port 993 -tls1 -showcerts -CAfile /usr/local/etc/ssl/cert.pem`

returns: `Verify return code: 0 (ok)`

It's a full Comodo CA signed cert chain. I don't think there is a cert chain problem and getting the X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN error is most likely the root CA cert, as those are self-signed, and means whatever command you're testing isn't pulling in a root trusted CA file.

the `/usr/local/etc/ssl/cert.pem` I have above is from NSS and not something I've locally trusted.

**Comment by rhavenn** [comment] 2015-06-26 04:55
side note. apparently the build I built from the source code was just falling through to the locally trusted certificate file. Moving the .imapfilter/certificates file and specifying `-t /usr/local/etc/ssl/` doesn't automatically trust the certificate and I'm still prompted to accept it. So, doesn't seem like it's picking up the CA root file?

**Comment by lefcha** [comment] 2015-06-26 05:08
@rhavenn I think something changed here, because yesterday I created a very simple imapfilter config with `server = 'secure.emailsrvr.com'`, and I added a line into imapfilter's `cert.c` file, in order to see why the verification fails. That's how I noticed that I got `X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN` on my Linux system, but today I don't get that, as the certificate verification using the system's CA TrustStore at `/etc/ssl/certs/` seems to go fine, and I get an authentication error by imapfilter, which is expected since I'm using a fake username and password.

**Comment by lefcha** [comment] 2015-06-26 05:18
Does FreeBSD have all the CA certificates inside one file ie. `/usr/local/share/ssl/cert.pem`?

Because I think that may be the problem.  On Linux it seems that the CA certificates are located in `/etc/ssl/certs`, and each file there contains on certificate.

I think that imapfilter uses the `SSL_CTX_load_verify_locations()` in a way that it is loading the certificates only from a `CApath` and not from a `CAfile`.  Can this be the cause of this?  I think you can try first with this command on your shell: 

```bash
openssl s_client -host secure.emailsrvr.com -port 993 -tls1 -showcerts -CApath /usr/local/etc/ssl/
```

**Comment by rhavenn** [comment] 2015-06-26 14:25
Yeah, CApath doesn't work. They're all in 1 file.

https://www.openssl.org/docs/ssl/SSL_CTX_load_verify_locations.html

seems to say that it will accept a CAFile. So, maybe add a if statement to your -t command that if -t is a file, pass it as the 2nd argument and if it's a dir, pass it as the 3rd?

**Comment by lefcha** [comment] 2015-06-26 17:53
Yes, that's what I suspected, and you have described exactly how this will be solved! Thanks, I'll provide a fix for this, and also revert the last commit so cert verification is more strict as before.

**Comment by Papafox** [comment] 2015-06-27 04:48
If secure.emailsrvr.com is following the SSL rules, you only need to have
the root certificate (AddTrust) in /etc/ssl/certs.  The intermediate certs
will be sent as part of the SSL handshake.  No need to change the
truststore param.

@rhavenn if you need to download the cert, you can find them here.
<https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/854/75/root-addtrustexternalcaroot>

On 27 June 2015 at 03:53, Lefteris Chatzimparmpas <notifications@github.com>
wrote:

> Yes, that's what I suspected, and you have described exactly how this will
> be solved! Thanks, I'll provide a fix for this, and also revert the last
> commit so cert verification is more strict as before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lefcha/imapfilter/issues/94#issuecomment-115811643>.
>



-- 
-----------------------------
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org

**Comment by lefcha** [comment] 2015-06-27 08:41
@Papafox I think the problem here is that @rhavenn and/or FreeBSD doesn't have a directory with the trusted CA certificates in a separate file one-by-one, but it has them all together in a file.

Maybe I misunderstood, but I think this problem would be solved if the user could supply just a CA file instead of a CA directory with the `-t` option.  Currently imapfilter loads only certificates from directories and fails to load them from a single file, but this can be fixes very easily.

**Comment by Papafox** [comment] 2015-06-27 11:15
Agreed, openssl has both -CAfile and -CApath options, so there must a be a
need for the two options.

As for my other point - only the root cert needs to be in the file, the
intermediate certs are downloaded during the SSL handshake.

On 27 June 2015 at 18:41, Lefteris Chatzimparmpas <notifications@github.com>
wrote:

> @Papafox <https://github.com/Papafox> I think the problem here is that
> @rhavenn <https://github.com/rhavenn> and/or FreeBSD doesn't have a
> directory with the trusted CA certificates in a separate file one-by-one,
> but it has them all together in a file.
>
> Maybe I misunderstood, but I think this problem would be solved if the
> user could supply just a CA file instead of a CA directory with the -t
> option. Currently imapfilter loads only certificates from directories and
> fails to load them from a single file, but this can be fixes very easily.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lefcha/imapfilter/issues/94#issuecomment-115986807>.
>



-- 
-----------------------------
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org

**Comment by lefcha** [comment] 2015-06-28 11:43
@rhavenn I have committed support for loading a CA truststore from a single file, so can you please try and see if this works for you?  You should just use it with something like `-t  /usr/local/etc/ssl/cert.pem`. Thanks, and I'll release 2.6.1 if this works for you...

**Comment by rhavenn** [comment] 2015-06-29 06:22
works like a charm. thanks.

I removed my .imapfilter/certificates files and used the -t option with a single cert.pem file and had no issues.

Thanks for working on that. I'll let the FreeBSD port maintainer know to update once you release.

**Comment by lefcha** [comment] 2015-06-29 06:31
That's great then, I'll release it now, thanks!

**Comment by lefcha** [comment] 2015-06-29 06:34
Closed by b337bdf26c85c58470a1414b53e5f39004b05df1.

**Closed by lefcha** 2015-06-29 06:34 UTC

**Comment by mmcco** [comment] 2015-07-18 23:22
For what it's worth, the OpenBSD port is now patching for this:

https://marc.info/?l=openbsd-ports&m=143726117214893&w=2

http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/mail/imapfilter/patches/patch-src_imapfilter_c   (hasn't synced in the commit yet)

I don't know whether there's a good way of dealing with it upstream. Maybe just checking for `/etc/ssl/cert.pem` if `/etc/ssl/certs` doesn't exist?

**Comment by lefcha** [comment] 2015-07-19 11:35
I just added support loading the `/etc/ssl/cert.pem` file, if `/etc/ssl/certs` dir doesn't exist.  If someone can try this on some BSD, it would be great, thanks!
